version: "3"
services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    command: --smallfiles
  learningpro-be:
    build:
      context: .
      dockerfile: learningpro/Dockerfile
    depends_on:
      - mongo-db
    ports:
      - 8080:8080
