server:
  port: 8081
  servlet :
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issue-uri: http://localhost:8083/auth/realms/learningpro
          jwk-set-uri: http://localhost:8083/auth/realms/learningpro/protocol/openid-connect/certs